//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.03.16 at 05:52:37 PM IST
//

package org.ucp.uaw;

import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.xml.bind.JAXBException;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.i18n.swing.util.Messages;
import org.i18n.swing.util.Utils;
import org.table.control.AbstractXMLTableDataModel;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}actor-weight&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *         &lt;element ref=&quot;{}total-UAW&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "actorWeight", "totalUAW" })
@XmlRootElement(name = "unadjusted-actor-weights")
public class UnadjustedActorWeights extends AbstractXMLTableDataModel<ActorWeight> {

  @XmlElement(name = "actor-weight", required = true)
  protected List<ActorWeight> actorWeight;
  @XmlElement(name = "total-UAW")
  protected double totalUAW;

  @SuppressWarnings("boxing")
  public UnadjustedActorWeights() {
    editableMap.put("type", false); //$NON-NLS-1$
    editableMap.put("description", false); //$NON-NLS-1$
    editableMap.put("weight", false); //$NON-NLS-1$
    editableMap.put("result", false); //$NON-NLS-1$
  }

  /**
   * Gets the value of the actorWeight property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
   * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
   * the actorWeight property.
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getActorWeight().add(newItem);
   * </pre>
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link ActorWeight }
   */
  public List<ActorWeight> getActorWeight() {
    if (actorWeight == null) {
      actorWeight = new ArrayList<ActorWeight>();
    }
    return this.actorWeight;
  }

  /**
   * Gets the value of the totalUAW property.
   */
  public double getTotalUAW() {
    return totalUAW;
  }

  /**
   * Sets the value of the totalUAW property.
   */
  public void setTotalUAW(double value) {
    this.totalUAW = value;
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.XMLTableDataModel#getTotalValue()
   */
  @Override
  public double getTotalValue() {
    double sum = 0;
    for (ActorWeight factor : actorWeight) {
      sum += factor.getResult();
    }
    setTotalUAW(sum);
    return sum;
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.XMLTableDataModel#getTypeClass()
   */
  @Override
  public Class<? extends ActorWeight> getTypeClass() {
    return ActorWeight.class;
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.TableElement#addRow(java.lang.Object)
   */
  @Override
  public void addRow(ActorWeight row) throws JAXBException {
    if (actorWeight.contains(row)) {
      throw new JAXBException(new Exception(MessageFormat
          .format(Messages.getString("row.already.exists"), row.getType()))); //$NON-NLS-1$
    }
    actorWeight.add(row);
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.TableElement#getAllRows()
   */
  @Override
  public List<ActorWeight> getAllRows() {
    return actorWeight;
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.TableElement#getColumnNames()
   */
  @Override
  public List<String> getColumnNames() {
    return Arrays.asList(Utils.getValuesCapitalized(getTypeClass().getAnnotation(XmlType.class).propOrder()));
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.TableElement#removeRow(java.lang.Object)
   */
  @Override
  public boolean removeRow(ActorWeight row) {
    return actorWeight.remove(row);
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.TableElement#updateRow(java.lang.Object)
   */
  @Override
  public void updateRow(ActorWeight row) {
    int index = actorWeight.indexOf(row);
    actorWeight.set(index, row);
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.AbstractTableDataModel#getElement()
   */
  @Override
  public ActorWeight getNewElement() {
    return new ActorWeight();
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.XMLTableDataModel#displayData()
   */
  @Override
  public String displayData() {
    StringBuilder builder = new StringBuilder();
    builder.append("UAW (Sum of Result) = "); //$NON-NLS-1$
    builder.append(getTotalUAW());
    return builder.toString();
  }

  /**
   * @return true if new rows can be added
   */
  @Override
  public boolean canAddRow() {
    return false;
  }
  
  /*
   * (non-Javadoc)
   * @see org.table.control.XMLTableDataModel#getCalculatedValue()
   */
  @Override
  public double getCalculatedValue() {
    return getTotalUAW();
  }
}
