//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.03.10 at 04:57:47 PM IST
//

package org.ucp.tcf;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * org.ucp.tcf package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _Weight_QNAME = new QName("", "weight"); //$NON-NLS-1$ //$NON-NLS-2$
  private final static QName _Complexity_QNAME = new QName("", "complexity"); //$NON-NLS-1$ //$NON-NLS-2$
  private final static QName _Factor_QNAME = new QName("", "factor"); //$NON-NLS-1$ //$NON-NLS-2$
  private final static QName _CalculatedFactor_QNAME = new QName("", "calculated-factor"); //$NON-NLS-1$ //$NON-NLS-2$
  private final static QName _TotalValue_QNAME = new QName("", "total-value"); //$NON-NLS-1$//$NON-NLS-2$
  private final static QName _CalculatedTcf_QNAME = new QName("", "calculated-tcf"); //$NON-NLS-1$//$NON-NLS-2$

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
   * org.ucp.tcf
   */
  public ObjectFactory() {
    // constructor
  }

  /**
   * Create an instance of {@link TechnicalFactor }
   */
  public TechnicalFactor createTechnicalFactor() {
    return new TechnicalFactor();
  }

  /**
   * Create an instance of {@link TechnicalComplexityFactors }
   */
  public TechnicalComplexityFactors createTechnicalComplexityFactors() {
    return new TechnicalComplexityFactors();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
   */
  @XmlElementDecl(namespace = "", name = "weight")
  public JAXBElement<Double> createWeight(Double value) {
    return new JAXBElement<Double>(_Weight_QNAME, Double.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
   */
  @XmlElementDecl(namespace = "", name = "complexity")
  public JAXBElement<Double> createComplexity(Double value) {
    return new JAXBElement<Double>(_Complexity_QNAME, Double.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
   */
  @XmlElementDecl(namespace = "", name = "calculated-factor")
  public JAXBElement<Double> createCalculatedFactor(Double value) {
    return new JAXBElement<Double>(_CalculatedFactor_QNAME, Double.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   */
  @XmlElementDecl(namespace = "", name = "factor")
  public JAXBElement<String> createFactor(String value) {
    return new JAXBElement<String>(_Factor_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
   */
  @XmlElementDecl(namespace = "", name = "total-value")
  public JAXBElement<Double> createTotalValue(Double value) {
    return new JAXBElement<Double>(_TotalValue_QNAME, Double.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
   */
  @XmlElementDecl(namespace = "", name = "calculated-tcf")
  public JAXBElement<Double> createCalculatedTcf(Double value) {
    return new JAXBElement<Double>(_CalculatedTcf_QNAME, Double.class, null, value);
  }
}
