//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.03.10 at 04:57:47 PM IST
//

package org.ucp.tcf;

import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.xml.bind.JAXBException;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.i18n.swing.util.Messages;
import org.i18n.swing.util.Utils;
import org.table.control.AbstractXMLTableDataModel;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}technical-factor&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "technicalFactor", "totalValue", "calculatedTcf" })
@XmlRootElement(name = "technical-complexity-factors")
public class TechnicalComplexityFactors extends AbstractXMLTableDataModel<TechnicalFactor> {

  @XmlElement(name = "technical-factor", required = true)
  protected List<TechnicalFactor> technicalFactor;
  @XmlElement(name = "total-value")
  protected double totalValue;
  @XmlElement(name = "calculated-tcf")
  protected double calculatedTcf;

  @SuppressWarnings("boxing")
  public TechnicalComplexityFactors() {
    editableMap.put("calculatedFactor", false); //$NON-NLS-1$
  }

  /**
   * Gets the value of the technicalFactor property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
   * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
   * the technicalFactor property.
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getTechnicalFactor().add(newItem);
   * </pre>
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link TechnicalFactor }
   */
  public List<TechnicalFactor> getTechnicalFactor() {
    if (technicalFactor == null) {
      technicalFactor = new ArrayList<TechnicalFactor>();
    }
    return this.technicalFactor;
  }

  /**
   * Gets the value of the calculatedTcf property.
   */
  public double getCalculatedTcf() {
    setCalculatedTcf(0.6 + (0.01 * totalValue));
    return calculatedTcf;
  }

  /**
   * Sets the value of the calculatedTcf property.
   */
  public void setCalculatedTcf(double value) {
    this.calculatedTcf = value;
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.XMLTableDataModel#getTotalValue()
   */
  @Override
  public double getTotalValue() {
    double sum = 0;
    for (TechnicalFactor factor : technicalFactor) {
      sum += factor.getCalculatedFactor();
    }
    setTotalValue(sum);
    return sum;
  }

  /**
   * Sets the value of the totalValue property.
   */
  public void setTotalValue(double value) {
    this.totalValue = value;
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.TableElement#addRow(java.lang.Object)
   */
  @Override
  public void addRow(TechnicalFactor row) throws JAXBException {
    if (technicalFactor.contains(row)) {
      throw new JAXBException(new Exception(MessageFormat
          .format(Messages.getString("row.already.exists"), row.getFactor()))); //$NON-NLS-1$
    }
    technicalFactor.add(row);
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.TableElement#getAllRows()
   */
  @Override
  public List<TechnicalFactor> getAllRows() {
    return technicalFactor;
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.TableElement#getColumnNames()
   */
  @Override
  public List<String> getColumnNames() {
    return Arrays.asList(Utils.getValuesCapitalized(getTypeClass().getAnnotation(XmlType.class).propOrder()));
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.TableElement#removeRow(java.lang.Object)
   */
  @Override
  public boolean removeRow(TechnicalFactor row) {
    return technicalFactor.remove(row);
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.TableElement#updateRow(java.lang.Object)
   */
  @Override
  public void updateRow(TechnicalFactor row) {
    int index = technicalFactor.indexOf(row);
    technicalFactor.set(index, row);
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.AbstractTableDataModel#getElement()
   */
  @Override
  public TechnicalFactor getNewElement() {
    return new TechnicalFactor();
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.XMLTableDataModel#getTypeClass()
   */
  @Override
  public Class<? extends TechnicalFactor> getTypeClass() {
    return TechnicalFactor.class;
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.XMLTableDataModel#displayData()
   */
  @Override
  public String displayData() {
    StringBuilder builder = new StringBuilder();
    builder.append("TCF (0.6 + (0.01*Total Factor)) = "); //$NON-NLS-1$
    builder.append(getCalculatedTcf());
    return builder.toString();
  }
  
  /*
   * (non-Javadoc)
   * @see org.table.control.XMLTableDataModel#getCalculatedValue()
   */
  @Override
  public double getCalculatedValue() {
    return getCalculatedTcf();
  }
}
