//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.03.16 at 05:14:16 PM IST
//

package org.ucp.uucw;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * org.ucp.uucw package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _Result_QNAME = new QName("", "result"); //$NON-NLS-1$ //$NON-NLS-2$
  private final static QName _Weight_QNAME = new QName("", "weight"); //$NON-NLS-1$ //$NON-NLS-2$
  private final static QName _NumCases_QNAME = new QName("", "num-cases"); //$NON-NLS-1$ //$NON-NLS-2$
  private final static QName _TotalUUCW_QNAME = new QName("", "total-UUCW"); //$NON-NLS-1$ //$NON-NLS-2$
  private final static QName _Type_QNAME = new QName("", "type"); //$NON-NLS-1$ //$NON-NLS-2$

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
   * org.ucp.uucw
   */
  public ObjectFactory() {
    // constructor
  }

  /**
   * Create an instance of {@link UsecaseWeight }
   */
  public UsecaseWeight createUsecaseWeight() {
    return new UsecaseWeight();
  }

  /**
   * Create an instance of {@link UnadjustedUsecaseWeights }
   */
  public UnadjustedUsecaseWeights createUnadjustedUsecaseWeights() {
    return new UnadjustedUsecaseWeights();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
   */
  @XmlElementDecl(namespace = "", name = "result")
  public JAXBElement<Double> createResult(Double value) {
    return new JAXBElement<Double>(_Result_QNAME, Double.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
   */
  @XmlElementDecl(namespace = "", name = "weight")
  public JAXBElement<Double> createWeight(Double value) {
    return new JAXBElement<Double>(_Weight_QNAME, Double.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
   */
  @XmlElementDecl(namespace = "", name = "num-cases")
  public JAXBElement<Double> createNumCases(Double value) {
    return new JAXBElement<Double>(_NumCases_QNAME, Double.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
   */
  @XmlElementDecl(namespace = "", name = "total-UUCW")
  public JAXBElement<Double> createTotalUUCW(Double value) {
    return new JAXBElement<Double>(_TotalUUCW_QNAME, Double.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   */
  @XmlElementDecl(namespace = "", name = "type")
  public JAXBElement<String> createType(String value) {
    return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
  }

}
