//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.03.16 at 05:14:16 PM IST
//

package org.ucp.uucw;

import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.xml.bind.JAXBException;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.i18n.swing.util.Messages;
import org.i18n.swing.util.Utils;
import org.table.control.AbstractXMLTableDataModel;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}usecase-weight&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *         &lt;element ref=&quot;{}total-UUCW&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "usecaseWeight", "totalUUCW" })
@XmlRootElement(name = "unadjusted-usecase-weights")
public class UnadjustedUsecaseWeights extends AbstractXMLTableDataModel<UsecaseWeight> {

  @XmlElement(name = "usecase-weight", required = true)
  protected List<UsecaseWeight> usecaseWeight;
  @XmlElement(name = "total-UUCW")
  protected double totalUUCW;

  @SuppressWarnings("boxing")
  public UnadjustedUsecaseWeights() {
    editableMap.put("type", false); //$NON-NLS-1$
    editableMap.put("description", false); //$NON-NLS-1$
    editableMap.put("weight", false); //$NON-NLS-1$
    editableMap.put("result", false); //$NON-NLS-1$
  }

  /**
   * Gets the value of the usecaseWeight property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
   * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
   * the usecaseWeight property.
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getUsecaseWeight().add(newItem);
   * </pre>
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link UsecaseWeight }
   */
  public List<UsecaseWeight> getUsecaseWeight() {
    if (usecaseWeight == null) {
      usecaseWeight = new ArrayList<UsecaseWeight>();
    }
    return this.usecaseWeight;
  }

  /**
   * Gets the value of the totalUUCW property.
   */
  public double getTotalUUCW() {
    return totalUUCW;
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.XMLTableDataModel#getTotalValue()
   */
  @Override
  public double getTotalValue() {
    double sum = 0;
    for (UsecaseWeight factor : usecaseWeight) {
      sum += factor.getResult();
    }
    setTotalUUCW(sum);
    return sum;
  }

  /**
   * Sets the value of the totalUUCW property.
   */
  public void setTotalUUCW(double value) {
    this.totalUUCW = value;
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.XMLTableDataModel#getTypeClass()
   */
  @Override
  public Class<? extends UsecaseWeight> getTypeClass() {
    return UsecaseWeight.class;
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.TableElement#addRow(java.lang.Object)
   */
  @Override
  public void addRow(UsecaseWeight row) throws JAXBException {
    if (usecaseWeight.contains(row)) {
      throw new JAXBException(new Exception(MessageFormat
          .format(Messages.getString("row.already.exists"), row.getType()))); //$NON-NLS-1$
    }
    usecaseWeight.add(row);
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.TableElement#getAllRows()
   */
  @Override
  public List<UsecaseWeight> getAllRows() {
    return usecaseWeight;
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.TableElement#getColumnNames()
   */
  @Override
  public List<String> getColumnNames() {
    return Arrays.asList(Utils.getValuesCapitalized(getTypeClass().getAnnotation(XmlType.class).propOrder()));
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.TableElement#removeRow(java.lang.Object)
   */
  @Override
  public boolean removeRow(UsecaseWeight row) {
    return usecaseWeight.remove(row);
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.TableElement#updateRow(java.lang.Object)
   */
  @Override
  public void updateRow(UsecaseWeight row) {
    int index = usecaseWeight.indexOf(row);
    usecaseWeight.set(index, row);
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.AbstractTableDataModel#getElement()
   */
  @Override
  public UsecaseWeight getNewElement() {
    return new UsecaseWeight();
  }

  /*
   * (non-Javadoc)
   * @see org.table.control.XMLTableDataModel#displayData()
   */
  @Override
  public String displayData() {
    StringBuilder builder = new StringBuilder();
    builder.append("UUCW (Sum of Result) = "); //$NON-NLS-1$
    builder.append(getTotalUUCW());
    return builder.toString();
  }

  /**
   * @return true if new rows can be added
   */
  @Override
  public boolean canAddRow() {
    return false;
  }
  
  /*
   * (non-Javadoc)
   * @see org.table.control.XMLTableDataModel#getCalculatedValue()
   */
  @Override
  public double getCalculatedValue() {
    return getTotalUUCW();
  }
}
