//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.03.16 at 05:14:16 PM IST
//

package org.ucp.uucw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}type&quot;/&gt;
 *         &lt;element name=&quot;description&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element ref=&quot;{}weight&quot;/&gt;
 *         &lt;element ref=&quot;{}num-cases&quot;/&gt;
 *         &lt;element ref=&quot;{}result&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "type", "description", "weight", "numCases", "result" })
@XmlRootElement(name = "usecase-weight")
public class UsecaseWeight {

  @XmlElement(required = true)
  protected String type;
  @XmlElement(required = true)
  protected String description;
  protected double weight;
  @XmlElement(name = "num-cases")
  protected double numCases;
  protected double result;

  /**
   * Gets the value of the type property.
   * @return possible object is {@link String }
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   * @param value
   *          allowed object is {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the description property.
   * @return possible object is {@link String }
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   * @param value
   *          allowed object is {@link String }
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the weight property.
   */
  public double getWeight() {
    return weight;
  }

  /**
   * Sets the value of the weight property.
   */
  public void setWeight(double value) {
    this.weight = value;
  }

  /**
   * Gets the value of the numCases property.
   */
  public double getNumCases() {
    return numCases;
  }

  /**
   * Sets the value of the numCases property.
   */
  public void setNumCases(double value) {
    this.numCases = value;
  }

  /**
   * Gets the value of the result property.
   */
  public double getResult() {
    setResult(weight * numCases);
    return result;
  }

  /**
   * Sets the value of the result property.
   */
  public void setResult(double value) {
    this.result = value;
  }

}
